### ISSUE TITLE
Command line arguments ?

### ISSUE THREAD

**Issue by githuborer** [d-jahren/RPCS3Updater#1]
Useful updater. 
There are command flags available for this ? Or could you please add some in the next release ?
Thank you

**Comment by d-jahren** [comment]
Thanks for the feedback! What type of features would you find useful/what command line args would you like to see?

**Comment by githuborer** [comment]
Hello, yes for the first:
-y -n would be nice to autoupdate without confirmation
-nightly or something similar.
You could implement all flags for autorunning the rpcs3.exe with its args: 
(rpcs3updater.exe --autorun-rom %romfile%)

Also consider to autorun the rpcs3 even if no update is available after your updater

**Comment by d-jahren** [comment]
@githuborer I've added three flags now, -y -h and -nolaunch. Didn't think that -nightly made sense since that's all they release now. Also with the rom one it would require more parsing that I won't have time to implement for a while. Hope it helps.
