### ISSUE TITLE
Will not work

### ISSUE THREAD

**Issue by Mawyman2316** [d-jahren/RPCS3Updater#2]
Using the debug and previous release of the updater yields this screen

[
![2018-06-17_21-10-28 jpg](https://user-images.githubusercontent.com/20804130/41515247-49218112-7273-11e8-8246-8801bb29ce53.jpg)
](url)

**Comment by Matipolit** [comment]
same issue

**Comment by d-jahren** [comment]
Hey sorry for the late response, I've been really busy with school lately. If the update functionality still hasn't  been implemented in RPCS3, I'm gonna redesign the program and make it work with github's APIs over winter break.

**Comment by d-jahren** [comment]
Hi all, this has been fixed in the latest release. Please check it out!
